before_install:
 - npm install -g grunt-cli
 - npm install -g bower

install:
 - npm install -d
 - bower install -d
 - webdriver-manager update

script:
  - grunt production

env:
  global:
  - secure: OAm/M2exphl1FGXcCtjI+C41quNZXrfLLVHJMKG8ydSHgswxfKrIu9cEQcgMZH/hfHlnxIBiXjXDQXFsgTCUlYbiUqEgZSYOpNN6yGZMUThxZyN1eOo7UexOYmWB2tZ/a6XZTJFH/6lHpphigcs8Izc9QAWHmeivdJrK+DiRxqs=
  - secure: RLLKjq6I+k+5vDmJqk/PC1Krm9Zo1VgAZlpeoLON5wgsTdMm5Z3dO3B8LtNsYG/+YhkctT5yG6hf18ehKypDz/5CAiq3ejPDWQrK+84I68zz81vj+TULy+WVM8WDf3oreK/ri0JXxm7jKbArsPzf3WubCEjLGkiBg3injdNWNdo=
